// Generated by Wrangler by running `wrangler types`

interface Env {
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_WEBHOOK_SECRET: string;
  ADMIN_CHAT_ID: string;
  MESSAGE_FEED_TOPIC_ID: string;
  LANGFUSE_HOST: string;
  LANGFUSE_PROJECT_ID: string;
  DATABASE_SERVICE: Fetcher;
}
