// Generated by Wrangler by running `wrangler types`

interface Env {
  EMBEDDER_SERVICE: Fetcher;
  AGENT_SERVICE: Fetcher;
  TRIVIAL_FILTER_SERVICE: Fetcher;
  BLACKLIST_SERVICE: Fetcher;
  CONSUMER: DurableObjectNamespace<
    import("./src/durable-objects/consumer").Consumer
  >;
  CONSUMER_KV: KVNamespace;
  NOTIFICATION_SERVICE: Fetcher;
  POLL_UPDATE_QUEUE: Queue<unknown>;
  AI_CHECKER_SERVICE: Fetcher;
  CHECKS_SERVICE: Fetcher;
  // Service bindings with custom methods
}
