packages:
  - workers/*
  - shared/*
  - evals
ignoredBuiltDependencies:
  - '@playwright/browser-chromium'
  - better-sqlite3
  - esbuild
  - sharp
  - workerd
onlyBuiltDependencies:
  - better-sqlite3
