// Generated by Wrangler by running `wrangler types`

// Generic database service types that allows any number of parameters
type DatabaseServiceMethod<TResult = any> = (
  ...args: any[]
) => Promise<TResult>;

type DatabaseServiceMethods = Record<string, DatabaseServiceMethod>;

interface Env {
  CHECKER_AGENT: DurableObjectNamespace<import("./src/index").CheckerAgent>;

  // Service bindings
  SEARCH_SERVICE: {
    search(params: any): Promise<any>;
  } & ServiceWorkerGlobalScope;

  SCREENSHOT_SERVICE: {
    screenshot(params: any): Promise<any>;
  } & ServiceWorkerGlobalScope;

  URLSCAN_SERVICE: {
    urlScan(params: any): Promise<any>;
  } & ServiceWorkerGlobalScope;

  EMBEDDER_SERVICE: {
    embed(params: any): Promise<any>;
  } & ServiceWorkerGlobalScope;

  DATABASE_SERVICE: DatabaseServiceMethods & ServiceWorkerGlobalScope;
  NOTIFICATION_SERVICE: Record<string, any> & ServiceWorkerGlobalScope;

  IMAGE_HASH_SERVICE: Fetcher;

  // R2 Buckets
  CHECKMATE_IMAGES_BUCKET: R2Bucket;

  // Queues
  CORE_CHECK_EVENTS_QUEUE: Queue<unknown>;

  // Environment variables
  LANGFUSE_PUBLIC_KEY: string;
  LANGFUSE_SECRET_KEY: string;
  LANGFUSE_HOST: string;
  ENVIRONMENT: string;
  IS_ROLLBACK: boolean;
  GEMINI_API_KEY: string;
  OPENAI_API_KEY: string;
  GROQ_API_KEY: string;
}
