// Generated by Wrangler by running `wrangler types`

interface Env {
  API_DOMAIN:
    | "https://screenshots.staging.checkmate.sg"
    | "https://screenshots.checkmate.sg";
  SCREENSHOT_BUCKET: R2Bucket;
  BROWSER: Fetcher;
}
