// Generated by Wrangler by running `wrangler types`

interface Env {
  API_DOMAIN:
    | "https://screenshots.staging.checkmate.sg"
    | "https://screenshots.checkmate.sg";
  SCREENSHOT_BUCKET: R2Bucket;
  BROWSER: Fetcher;
  SCREENSHOT_ONE_ACCESS_KEY: string;
  SCREENSHOT_ONE_SECRET_KEY: string;
}
