// Generated by Wrangler by running `wrangler types`

// Import types from the database service

// Generic database service types that allows any number of parameters
type DatabaseServiceMethod<TResult = any> = (
  ...args: any[]
) => Promise<TResult>;

type DatabaseServiceMethods = Record<string, DatabaseServiceMethod>;

interface Env {
  DATABASE_SERVICE: DatabaseServiceMethods & ServiceWorkerGlobalScope;
  NOTIFICATION_SERVICE: NotificationServiceMethods & ServiceWorkerGlobalScope;

  CORE_CHECK_EVENTS_QUEUE: Queue<unknown>;
}
