name: Deploy Portkey to CF Worker
# Trigger the workflow on pushes to staging/main branches when worker code changes
# or manually via workflow_dispatch with optional parameters
on:
  push:
    branches:
      - staging
      - main
    paths:
      - "workers/portkey-service/**" # Only run when portkey code changes

  workflow_dispatch:
    inputs:
      force_deploy:
        description: Force deploy Portkey
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    name: "Deploy Portkey to ${{  github.ref_name == 'main' && 'production' || github.ref_name }}"
    runs-on: ubuntu-latest
    environment: "${{  github.ref_name == 'main' && 'production' || github.ref_name }}"
    timeout-minutes: 60 # Set timeout to prevent hung deployments
    steps:
      - name: Checkout Portkey Gateway
        uses: actions/checkout@v4.2.2
        with:
          repository: Portkey-AI/gateway
          path: .

      - name: Checkout Worker Code
        uses: actions/checkout@v4.2.2
        with:
          path: ai-monorepo

      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.5.2

      - name: Deploy Portkey with Wrangler CLI
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |-
          ENV_NAME="${{ github.ref_name == 'main' && 'production' || github.ref_name }}"

          # Deploy the worker
          mv ./ai-monorepo/workers/portkey-service/* ./
          npm install
          npx wrangler deploy --env $ENV_NAME --config ./wrangler.jsonc

